// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control_msgs.proto
// Original file comments:
// Created by Gwanwoo Kim on 2021-05-28.
// Copyright 2021 Neuromeka Inc. All rights reserved.
//
#ifndef GRPC_control_5fmsgs_2eproto__INCLUDED
#define GRPC_control_5fmsgs_2eproto__INCLUDED

#include "control_msgs.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace IndyFramework {
namespace Protobuf {
namespace Control {

}  // namespace Control
}  // namespace Protobuf
}  // namespace IndyFramework


#endif  // GRPC_control_5fmsgs_2eproto__INCLUDED
